import { SIZE_SPECS } from "@/infrastructure/simulation/model";
import type { Customer, DocumentRec, Station } from "@/domain/model";

/** Renders a DOM node (charts + text in any language/font) into a multi-page A4 PDF. */
export async function exportNodeToPdf(node: HTMLElement, filename: string) {
  const [{ jsPDF }, { toPng }] = await Promise.all([import("jspdf"), import("html-to-image")]);
  const toJpeg = (n: HTMLElement, o: Parameters<typeof toPng>[1]) => import("html-to-image").then((m) => m.toJpeg(n, { ...o, quality: 0.88 }));
  const dataUrl = await toJpeg(node, { pixelRatio: 1.6, backgroundColor: "#ffffff", cacheBust: true }).catch(() => toJpeg(node, { pixelRatio: 1.6, backgroundColor: "#ffffff", skipFonts: true }));
  const img = new Image();
  img.src = dataUrl;
  await img.decode();
  const pdf = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = 210, pageH = 297, margin = 10;
  const w = pageW - margin * 2;
  const h = (img.height * w) / img.width;
  let y = 0;
  const usable = pageH - margin * 2;
  while (y < h) {
    if (y > 0) pdf.addPage();
    pdf.addImage(dataUrl, "JPEG", margin, margin - y, w, h);
    y += usable;
  }
  pdf.save(filename);
}

/** Demo stand-in for stored documents (warranty, certificates, manuals). */
export async function generateDocumentPdf(doc: DocumentRec, station: Station, customer?: Customer) {
  const { jsPDF } = await import("jspdf");
  const spec = SIZE_SPECS[station.size];
  const pdf = new jsPDF({ unit: "mm", format: "a4" });
  pdf.setFillColor(34, 56, 47);
  pdf.rect(0, 0, 210, 28, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("ARMEN Care", 14, 17);
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.text("Modular battery energy storage · Armenia", 14, 23);
  pdf.setTextColor(20, 30, 25);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text(doc.title, 14, 44);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  const rows: [string, string][] = [
    ["Station", station.name],
    ["Customer", customer?.name ?? "—"],
    ["Model", `${spec.model} (${spec.capacityKwh} kWh, ${spec.modules} x 5 kWh LFP modules, ${spec.inverterKw} kW inverter)`],
    ["Serial number", station.serial],
    ["Address", station.address],
    ["Installation date", station.install_date],
    ["Warranty", `10 years, valid until ${station.warranty_end}`],
    ["Document date", doc.created_at.slice(0, 10)],
  ];
  let y = 58;
  for (const [k, v] of rows) {
    pdf.setFont("helvetica", "bold");
    pdf.text(k, 14, y);
    pdf.setFont("helvetica", "normal");
    pdf.text(pdf.splitTextToSize(v, 130), 64, y);
    y += 9;
  }
  const bodies: Record<DocumentRec["kind"], string> = {
    warranty: "ARMEN warrants the battery modules, battery management system, power conversion system, cooling and fire-suppression equipment against defects for 10 years from installation. Battery capacity is warranted at a minimum of 70% state of health at the end of the warranty period, provided scheduled maintenance (6-monthly inspection, annual coolant and fire-system check) is carried out by ARMEN technicians.",
    installation_certificate: "The energy storage station was installed, inspected and commissioned according to the ARMEN installation procedure. DC connections were torque-checked, the cooling loop was pressure-tested, the water-based fire suppression system was armed and tested, and grid connection and communication (CAN/Modbus) were verified.",
    manual: "This manual describes normal operation, the HMI panel, operating modes (maximize self-consumption / keep backup reserve), the ARMEN Care app, and routine checks the owner can perform. Never open the cabinet: all internal work must be done by ARMEN technicians.",
    safety_manual: "If the fire alarm sounds: leave the building, keep others away, call 911 and 101, do not open the cabinet and do not use water on the cabinet yourself. The built-in suppression system floods only the damaged compartment with 50-55 L of water in about 50 seconds (60 L/min).",
    service_report: "Service was completed according to the digital checklist. All findings, parts used and photos are recorded in the ARMEN Care work order. The customer signed the report on completion.",
  };
  pdf.setFontSize(11);
  pdf.text(pdf.splitTextToSize(bodies[doc.kind], 182), 14, y + 8);
  pdf.setFontSize(8);
  pdf.setTextColor(120, 120, 120);
  pdf.text("Demo document generated by ARMEN Care. In production this file is stored in Supabase Storage.", 14, 287);
  pdf.save(`${doc.title.replace(/[^\w-]+/g, "_")}.pdf`);
}
